namespace ScooterApp.Services.NinebotESX
{
   public enum ESXCommand
    {
        READ_REGISTER = 0x01,
        WRITE_REGISTER_WR = 0X02,
        WRITE_REGISTER = 0x03,
        RESPONSE_TO_READ_REGISTER = 0x04,
        RESPONSE_TO_WRITE_REGISTER = 0x05,
        FIRMWARE_START_FRAME = 0x07,
        FIRMWARE_DATA_FRAME = 0x08,
        FIRMWARE_VERIFY_FRAME = 0x09,
        CPU_RESET_AFTER_UPDATE = 0x0A,
        FIRMWARE_RESPONSE = 0x0B,
        PROGRAM_SERIAL_NUMBER = 0x18,
        SET_SCOOTER_NAME = 0x50,
        REFRESH_STATUS = 0x52,
        HEARTBEAT = 0x55,
        ACTIVATE_WITH_SPEED_LIMIT = 0x57,
        FACTORY_RESET = 0x58,
        ACTIVATE_WITHOUT_SPEED_LIMIT = 0x59,
        USER_RESET_PIN_AND_SETTINGS = 0x5A,
        START_AUTHENTIFICATION = 0x5B,
        ASK_PRESS_BUTTON = 0x5C,
        CONFIRM_AUTHENTIFICATION = 0x5D,
        SET_ODOMETER = 0x5C,
        READ_REGISTERS_UPDATE_BLE_INPUTS = 0x61,
        UPDATE_BLE_OUTPUTS = 0x64,
        UPDATE_BLE_INPUTS = 0x65
    }
}
